/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages.Technician;

import Helper.DeselectOnReselectModel;
import Helper.SharedHelper;
import Models.Database;
import Models.Service;
import Models.User;
import Pages.LoginPage;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sphal
 */
public class ManageServicePage extends javax.swing.JFrame {
    private int selectedRowIndex = -1;

    /**
     * Creates new form ManageServicePage
     */
    public ManageServicePage() {
        initComponents();
        this.setVisible(true);
        DefaultComboBoxModel areas = new DefaultComboBoxModel();
        for (String area: Service.getAreas()) {
            areas.addElement(area);
        }
        areaField.setModel(areas);
        serviceTable.setSelectionModel(new DeselectOnReselectModel());
        serviceTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    if (selectedRowIndex == serviceTable.getSelectedRow()) {
                        selectedRowIndex = -1;
                        serviceTable.getSelectionModel().clearSelection();
                    }
                    
                    if (serviceTable.getSelectedRow() == -1) {
                        titleField.setText("");
                        descField.setText("");
                        priceField.setText("");
                        areaField.setSelectedIndex(0);
                        return;
                    }
                    
                    selectedRowIndex = serviceTable.getSelectedRow();
                    titleField.setText(serviceTable.getValueAt(serviceTable.getSelectedRow(), 0).toString());
                    descField.setText(serviceTable.getValueAt(serviceTable.getSelectedRow(), 1).toString());
                    priceField.setText(serviceTable.getValueAt(serviceTable.getSelectedRow(), 2).toString());
                    String selectedArea = serviceTable.getValueAt(serviceTable.getSelectedRow(), 3).toString();
                    areaField.setSelectedIndex(SharedHelper.indexOf(Service.getAreas(), selectedArea));    
                }
            }
        });
    }
    
    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        refreshTable();
    }
    
    private void refreshTable() {
        String[] columns = {"Service Title", "Service Desc", "Price", "Area"};
        DefaultTableModel serviceTableModel = new DefaultTableModel(columns, 0);
        for (Service service: Database.getServices()) {
            if (service.getTechnicianEmail().equals(LoginPage.technicianPage.getLoginEmail())) {
                serviceTableModel.addRow(new Object[] {
                service.getTitle(),
                service.getDescription(),
                service.getPrice(),
                service.getServiceArea()
            });
            }
        }
        serviceTable.setModel(serviceTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bluePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviceTable = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        descField = new javax.swing.JTextField();
        descLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        areaLabel = new javax.swing.JLabel();
        areaField = new javax.swing.JComboBox<>();
        createUpdateBtn = new javax.swing.JButton();
        headingLabel = new javax.swing.JLabel();
        formMessage = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MANAGE SERVICES");

        bluePanel.setBackground(new java.awt.Color(35, 57, 91));

        serviceTable.setBackground(new java.awt.Color(64, 110, 142));
        serviceTable.setFont(new java.awt.Font("Perpetua Titling MT", 0, 10)); // NOI18N
        serviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service Title", "Service Desc", "Price", "Area"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        serviceTable.setGridColor(new java.awt.Color(64, 110, 142));
        serviceTable.setPreferredSize(new java.awt.Dimension(300, 365));
        jScrollPane1.setViewportView(serviceTable);

        titleLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("service title");

        descLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        descLabel.setForeground(new java.awt.Color(255, 255, 255));
        descLabel.setText("service description");

        priceLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("price");

        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });

        areaLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        areaLabel.setForeground(new java.awt.Color(255, 255, 255));
        areaLabel.setText("service area");

        areaField.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        areaField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        createUpdateBtn.setBackground(new java.awt.Color(64, 110, 142));
        createUpdateBtn.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        createUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        createUpdateBtn.setText("CREATE/UPDATE");
        createUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUpdateBtnActionPerformed(evt);
            }
        });

        headingLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setText("SERVICES");

        formMessage.setFont(new java.awt.Font("Perpetua Titling MT", 0, 10)); // NOI18N
        formMessage.setForeground(new java.awt.Color(255, 0, 51));

        backBtn.setBackground(new java.awt.Color(64, 110, 142));
        backBtn.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bluePanelLayout = new javax.swing.GroupLayout(bluePanel);
        bluePanel.setLayout(bluePanelLayout);
        bluePanelLayout.setHorizontalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(headingLabel))
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bluePanelLayout.createSequentialGroup()
                                .addComponent(areaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bluePanelLayout.createSequentialGroup()
                                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(areaField, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(descField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bluePanelLayout.createSequentialGroup()
                                        .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(descLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(priceLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 57, Short.MAX_VALUE))
                                    .addComponent(createUpdateBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30))
                            .addGroup(bluePanelLayout.createSequentialGroup()
                                .addComponent(formMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        bluePanelLayout.setVerticalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(headingLabel)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(descLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(priceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(areaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(areaField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formMessage)
                        .addGap(18, 18, 18)
                        .addComponent(createUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bluePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bluePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        LoginPage.technicianPage.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUpdateBtnActionPerformed
        String serviceTitle = titleField.getText();
        String serviceDesc = descField.getText();
        Double price = Double.parseDouble(priceField.getText());
        String selectedArea = areaField.getSelectedItem().toString();
        
        if (serviceTitle.length() < 1 ||
                    serviceDesc.length() < 1 ||
                    price < 0 ||
                    selectedArea.length() < 1) {
            formMessage.setText("Invalid details, please try again.");
            formMessage.setForeground(Color.red);
            return;
        }
        
        Service service = new Service(LoginPage.technicianPage.getLoginEmail(), serviceTitle, serviceDesc, price, selectedArea);
        if (selectedRowIndex != -1) {
            Database.updateService(service, selectedRowIndex);
            formMessage.setText("Successfully updated!");
        } else {
            Database.addService(service);
            formMessage.setText("Successfully added!");            
        }
        
        Database.writeToServices();
        refreshTable();
        formMessage.setForeground(Color.green);
    }//GEN-LAST:event_createUpdateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageServicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageServicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageServicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageServicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageServicePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> areaField;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bluePanel;
    private javax.swing.JButton createUpdateBtn;
    private javax.swing.JTextField descField;
    private javax.swing.JLabel descLabel;
    private javax.swing.JLabel formMessage;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTable serviceTable;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
