/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages.Technician;

import Helper.DeselectOnReselectModel;
import Helper.SharedHelper;
import Models.Database;
import Models.Service;
import Models.User;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author sphal
 */
public class ManageAppointmentPage extends javax.swing.JFrame {
    private int selectedRowIndex = -1;

    /**
     * Creates new form ManageAppointmentPage
     */
    public ManageAppointmentPage() {
        initComponents();
        DefaultComboBoxModel customers = new DefaultComboBoxModel();
        for (User user: Database.getUsers()) {
            if (user.getRole().equals("customer")) {
                customers.addElement(user);
            }
        }
        custEmailField.setModel(customers);
        appointmentTable.setSelectionModel(new DeselectOnReselectModel());
        appointmentTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    if (selectedRowIndex == appointmentTable.getSelectedRow()) {
                        selectedRowIndex = -1;
                        appointmentTable.getSelectionModel().clearSelection();
                    }
                    if (appointmentTable.getSelectedRow() == -1) {
                        serviceNameField.setSelectedIndex(0);
                        custEmailField.setSelectedIndex(0);
                        startDateField.setText("");
                        endDateField.setText("");
                        return;
                    }
                    selectedRowIndex = appointmentTable.getSelectedRow();
                    
                    Service selectedService = Database.findService(appointmentTable.getValueAt(appointmentTable.getSelectedRow(), 0).toString());
                    User selectedCust = Database.findUser(appointmentTable.getValueAt(appointmentTable.getSelectedRow(), 1).toString());
                    serviceNameField.setSelectedIndex(SharedHelper.indexOf(Database.getServices(), selectedService));
                    custEmailField.setSelectedIndex(SharedHelper.indexOf(Database.getUsers(), selectedCust));
                    startDateField.setText(appointmentTable.getValueAt(appointmentTable.getSelectedRow(), 2).toString());
                    endDateField.setText(appointmentTable.getValueAt(appointmentTable.getSelectedRow(), 3).toString());                  
                    }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bluePanel = new javax.swing.JScrollPane();
        appointmentTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        serviceNameLabel = new javax.swing.JLabel();
        startDateField = new javax.swing.JTextField();
        endDateLabel = new javax.swing.JLabel();
        custEmailLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        endDateField = new javax.swing.JTextField();
        createUpdateBtn = new javax.swing.JButton();
        endDateFieldMsg = new javax.swing.JLabel();
        headingLabel = new javax.swing.JLabel();
        startDateFieldMsg = new javax.swing.JLabel();
        formMessage = new javax.swing.JLabel();
        serviceNameField = new javax.swing.JComboBox<>();
        custEmailField = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(35, 57, 91));

        appointmentTable.setBackground(new java.awt.Color(64, 110, 142));
        appointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service Name", "Cust Email", "Start DateTime", "End DateTime"
            }
        ));
        appointmentTable.setGridColor(new java.awt.Color(64, 110, 142));
        appointmentTable.setPreferredSize(new java.awt.Dimension(300, 335));
        bluePanel.setViewportView(appointmentTable);

        backBtn.setBackground(new java.awt.Color(64, 110, 142));
        backBtn.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        backBtn.setText("Back");

        serviceNameLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        serviceNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        serviceNameLabel.setText("SERVICE NAME");

        endDateLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        endDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        endDateLabel.setText("ENDING DATE");

        custEmailLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        custEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        custEmailLabel.setText("CUSTOMER EMAIL");

        startDateLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        startDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        startDateLabel.setText("STARTING DATE");

        createUpdateBtn.setBackground(new java.awt.Color(64, 110, 142));
        createUpdateBtn.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        createUpdateBtn.setText("CREATE/UPDATE");

        endDateFieldMsg.setFont(new java.awt.Font("Perpetua Titling MT", 0, 10)); // NOI18N
        endDateFieldMsg.setForeground(new java.awt.Color(255, 0, 0));

        headingLabel.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(255, 255, 255));
        headingLabel.setText("Appointments");

        startDateFieldMsg.setFont(new java.awt.Font("Perpetua Titling MT", 0, 10)); // NOI18N
        startDateFieldMsg.setForeground(new java.awt.Color(255, 0, 0));

        formMessage.setFont(new java.awt.Font("Perpetua Titling MT", 0, 10)); // NOI18N
        formMessage.setForeground(new java.awt.Color(255, 0, 0));

        serviceNameField.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        serviceNameField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        custEmailField.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        custEmailField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backBtn)
                    .addComponent(serviceNameLabel)
                    .addComponent(startDateField)
                    .addComponent(custEmailLabel)
                    .addComponent(startDateLabel)
                    .addComponent(endDateLabel)
                    .addComponent(endDateField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(createUpdateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endDateFieldMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startDateFieldMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serviceNameField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(custEmailField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bluePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headingLabel))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(headingLabel))
                .addGap(24, 24, 24)
                .addComponent(serviceNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(serviceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(custEmailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(startDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startDateFieldMsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endDateFieldMsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formMessage))
                    .addComponent(bluePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAppointmentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAppointmentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAppointmentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAppointmentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAppointmentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable appointmentTable;
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane bluePanel;
    private javax.swing.JButton createUpdateBtn;
    private javax.swing.JComboBox<String> custEmailField;
    private javax.swing.JLabel custEmailLabel;
    private javax.swing.JTextField endDateField;
    private javax.swing.JLabel endDateFieldMsg;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JLabel formMessage;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> serviceNameField;
    private javax.swing.JLabel serviceNameLabel;
    private javax.swing.JTextField startDateField;
    private javax.swing.JLabel startDateFieldMsg;
    private javax.swing.JLabel startDateLabel;
    // End of variables declaration//GEN-END:variables
}
