/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages.Customer;

import Helper.DeselectOnReselectModel;
import Helper.SharedHelper;
import Models.Database;
import Models.Service;
import Models.User;
import java.awt.Color;
import java.util.Arrays;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yyhao0422
 */
public class CheckServicePage extends javax.swing.JFrame {
    

    /**
     * Creates new form CheckServicePage
     */
    public String email;
    public Object[] selectedData;
    public CheckServicePage() {
        initComponents();
        serviceTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e){
                if (!e.getValueIsAdjusting()) { // Ensure the event is not still adjusting
                    int selectedRow = serviceTable.getSelectedRow();
                    if (selectedRow != -1) { // Check if any row is selected
                        // Retrieve the row data from the table model
                        Object[] rowData = new Object[serviceTable.getColumnCount()];
                        for (int i = 0; i < rowData.length; i++) {
                            rowData[i] = serviceTable.getValueAt(selectedRow, i);
                        }
                        // Now you have access to the rowData array representing the selected row
                        // You can perform any action with it
                        selectedData = rowData; 
                        
                    }
                }
            }
            
        });
        populateServiceTable();
    }
    
    
    private void populateServiceTable(){
     Service[] services= Database.getServices();
        
     String[] columns ={"Service Title","Service Desc","Price","Area"};
     DefaultTableModel serviceTableModel = new DefaultTableModel(columns,0);
     for (Service service : services){
         serviceTableModel.addRow(new Object[]{
             service.getTitle(),
             service.getTechnicianEmail(),
             service.getPrice(),
             service.getServiceArea(),
         });
     }       
     serviceTable.setModel(serviceTableModel);   
    }
    
    public void setLoginEmail(String email) {
        this.email = email;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        serviceTable = new javax.swing.JTable();
        addServiceButton = new javax.swing.JButton();
        handleExit = new javax.swing.JButton();
        formMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        serviceTable.setBackground(new java.awt.Color(64, 110, 142));
        serviceTable.setFont(new java.awt.Font("Perpetua Titling MT", 0, 10)); // NOI18N
        serviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service Title", "Technician Email", "Price", "Area"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        serviceTable.setGridColor(new java.awt.Color(64, 110, 142));
        serviceTable.setPreferredSize(new java.awt.Dimension(300, 365));
        serviceTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serviceTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(serviceTable);

        addServiceButton.setText("Add Service");
        addServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addServiceButtonActionPerformed(evt);
            }
        });

        handleExit.setText("Exit");
        handleExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addServiceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(handleExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(addServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(formMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(handleExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addServiceButtonActionPerformed
        // TODO add your handling code here:
        System.out.println(selectedData);
        
        if(selectedData != null){       
            MakeAppointmentPage makeAppointmentPage = new MakeAppointmentPage();
            makeAppointmentPage.setVisible(true);
            makeAppointmentPage.setSelectedServiceData(selectedData);
            makeAppointmentPage.setloginEmail(email);
            makeAppointmentPage.populateAppointmentData();
        }else{
            formMessage.setText("Please Select a service !");
            formMessage.setForeground(Color.red);
        }
    }//GEN-LAST:event_addServiceButtonActionPerformed

    private void handleExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_handleExitActionPerformed

    private void serviceTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serviceTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceTableKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckServicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckServicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckServicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckServicePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckServicePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addServiceButton;
    private javax.swing.JLabel formMessage;
    private javax.swing.JButton handleExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable serviceTable;
    // End of variables declaration//GEN-END:variables
}
